<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>proof-of-life-web</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <ContainerImageName>proof-of-life-web</ContainerImageName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="9.0.0" />
    <PackageReference Include="Microsoft.Identity.Web" Version="3.3.0" />
    <PackageReference Include="Microsoft.Identity.Web.MicrosoftGraph" Version="3.3.0" />
    <PackageReference Include="Microsoft.Identity.Web.UI" Version="3.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProofOfLife.ServiceDefaults\ProofOfLife.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
